In [1]:
import cv2
import import_ipynb
import object_detection

importing Jupyter notebook from object_detection.ipynb


In [2]:
# Get a list of jpeg image files containing traffic lights
files = object_detection.get_files('traffic_light_input/*.jpg')
 
# Load the object detection model
this_model = object_detection.load_ssd_coco()
 
# Keep track of the number of traffic lights found
traffic_light_count = 0
 
# Keep track of the number of image files that were processed
file_count = 0
 
# Display a count of the number of images we need to process
print("Number of Images:", len(files))
 
# Go through each image file, one at a time
for file in files:
 
  # Detect objects in the image
  # img_rgb is the original image in RGB format
  # out is a dictionary containing the results of object detection
  # file_name is the name of the file
  (img_rgb, out, file_name) = object_detection.perform_object_detection(model=this_model, file_name=file, save_annotated=None, model_traffic_lights=None)
     
  # Every 10 files that are processed
  if (file_count % 10) == 0:
 
    # Display a count of the number of files that have been processed
    print("Images processed:", file_count)
 
    # Display the total number of traffic lights that have been identified so far
    print("Number of Traffic lights identified: ", traffic_light_count)
         
  # Increment the number of files by 1
  file_count = file_count + 1
 
  # For each traffic light (i.e. bounding box) that was detected
  for idx in range(len(out['boxes'])):
 
    # Extract the type of object that was detected  
    obj_class = out["detection_classes"][idx]
         
    # If the object that was detected is a traffic light
    if obj_class == object_detection.LABEL_TRAFFIC_LIGHT:
         
      # Extract the coordinates of the bounding box
      box = out["boxes"][idx]
             
      # Extract (i.e. crop) the traffic light from the image     
      traffic_light = img_rgb[box["y"]:box["y2"], box["x"]:box["x2"]]
             
      # Convert the traffic light from RGB format into BGR format
      traffic_light = cv2.cvtColor(traffic_light, cv2.COLOR_RGB2BGR)
 
      # Store the cropped image in a folder named 'traffic_light_cropped'     
      cv2.imwrite("traffic_light_cropped/" + str(traffic_light_count) + ".jpg", traffic_light)
             
      # Increment the number of traffic lights by 1
      traffic_light_count = traffic_light_count + 1
 
# Display the total number of traffic lights identified
print("Number of Traffic lights identified:", traffic_light_count)

244817203/244817203 [==============================] - 34s 0us/step
Model path:  /root/.keras/datasets/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8


2023-07-20 01:38:37.364815: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 9437184 exceeds 10% of free system memory.
2023-07-20 01:38:37.390921: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 8388608 exceeds 10% of free system memory.
2023-07-20 01:38:37.429155: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 9437184 exceeds 10% of free system memory.
2023-07-20 01:38:37.597775: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 9437184 exceeds 10% of free system memory.


Number of Images: 9


2023-07-20 01:38:38.419314: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 8997282 exceeds 10% of free system memory.


num_detections: tf.Tensor([100.], shape=(1,), dtype=float32) 100
Detection classes: [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 47. 10. 10. 79. 10.  1. 82.
 62. 10. 78. 10.  1. 10. 10. 10. 10. 10. 10. 10. 10. 10. 84. 84. 10. 10.
  9.  3. 84. 10. 84. 84. 84. 10. 33. 84. 72. 10. 10. 84.  8. 10. 33.  8.
 10. 10. 10. 84. 84.  3. 44.  3.  8. 22. 10. 84. 47. 78. 10. 10. 13. 10.
  6. 88. 10. 55. 70. 88. 10. 10. 55. 10. 10. 78. 10. 88.  7. 10. 84. 10.
  8. 10. 82.  6. 10. 84.  1. 84.  4. 84.]
Detection Boxes: [[3.88260186e-01 4.07115072e-01 8.38916838e-01 5.40083647e-01]
 [3.68255198e-01 5.55907369e-01 8.30238760e-01 6.82998419e-01]
 [3.52673173e-01 4.09577191e-01 8.65386605e-01 6.71298325e-01]
 [4.08091068e-01 4.08206165e-01 7.31325865e-01 5.14015734e-01]
 [3.38831306e-01 5.37398398e-01 3.93468142e-01 6.50965393e-01]
 [3.71649086e-01 5.34285426e-01 8.21905911e-01 6.46906972e-01]
 [2.74595678e-01 3.79666626e-01 8.85830462e-01 7.55130351e-01]
 [3.39064151e-01 5.90476751e-01 3.81808907e-01 6.53